@baseUrl = http://127.0.0.1:8027
@apiKey = xxx
@serverKey = github
@clientInfo = {"name": "chatwise", "version": "0.0.1"}

### list servers
POST {{baseUrl}}/v1/list-servers
Content-Type: application/json
Authorization: Bearer {{apiKey}}
X-Client-Info: {{clientInfo}}

{
  "page": 1,
  "limit": 30
}

### get server tools
POST {{baseUrl}}/v1/list-tools
Content-Type: application/json
Authorization: Bearer {{serverKey}}
X-Client-Info: {{clientInfo}}

### call tool
POST {{baseUrl}}/v1/call-tool
Content-Type: application/json
Authorization: Bearer {{serverKey}}
X-Client-Info: {{clientInfo}}

{
  "name": "search_repositories",
  "arguments": {
    "query": "shipany"
  }
}
